### ISSUE TITLE
Package versions have conflicting dependencies

### ISSUE THREAD

**Issue by rookiestar28** [sdbds/SVD-webui#1]
![螢幕擷取畫面 2023-11-24 102454](https://github.com/sdbds/SVD-webui/assets/151893693/cd331cd0-6e5e-4ebd-9e78-36b54c4014d8)

How should this problem be solved?

**Comment by harkonkr** [comment]
use torchdata==0.7.1

**Comment by sdbds** [comment]
> ![螢幕擷取畫面 2023-11-24 102454](https://user-images.githubusercontent.com/151893693/285346797-cd331cd0-6e5e-4ebd-9e78-36b54c4014d8.png)
> 
> How should this problem be solved?

update requirements now
